<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('bookable_services', function (Blueprint $table) {
                        // Add a unique constraint on the combination of these two columns.
            $table->unique(['tenant_id', 'name']);

        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('bookable_services', function (Blueprint $table) {
            // The name of the index is auto-generated by Laravel as:
            // tablename_column1_column2_unique
            $table->dropUnique('bookable_services_tenant_id_name_unique');
        });
    }
};
